import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :botchini, BotchiniWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Botchini.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Enable OpenTelemetry OTLP trace export in production
config :opentelemetry,
  span_processor: :batch,
  traces_exporter: :otlp

# PromEx - start a dedicated metrics server for Prometheus scraping
config :botchini, Botchini.PromEx, metrics_server: [port: 4021, path: "/metrics"]

# Structured JSON logging for Loki ingestion
config :logger, :default_handler, formatter: {LoggerJSON.Formatters.Basic, [metadata: :all]}

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
