name: Deploy
on:
  push:
    branches:
      - main
jobs:
  push_to_registry:
    name: Push image to DockerHub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2

      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: lucapasquale094/botchini
          tag_with_ref: true
          tag_with_sha: true

  deploy:
    name: Deploy
    runs-on: ubuntu-18.04
    needs: push_to_registry
    steps:
    - uses: actions/checkout@v2

    - name: Add SHORT_SHA env property with commit short sha
      run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV

    - uses: floms/action-caprover@v1
      with:
        app: 'botchini'
        host: 'https://captain.lucapasquale.dev'
        password: '${{ secrets.CAPROVER_PASSWORD }}'
        image: lucapasquale094/botchini:sha-${{ env.SHORT_SHA }}
