name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - uses: floms/action-caprover@v1
      with:
        app: 'botchini'
        host: 'https://captain.lucapasquale.dev'
        password: '${{ secrets.CAPROVER_PASSWORD }}'
        branch: 'main'
