name: PR Checks

on: pull_request

env:
  MIX_ENV: test
  ELIXIR_VER: 1.11.2
  OTP_VER: 23

jobs:
  test:
    runs-on: ubuntu-18.04
    services:
      db:
        image: postgres:11
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2

    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: ${{ env.ELIXIR_VER }}
        otp-version: ${{ env.OTP_VER }}

    - name: Retrieve Mix Dependencies Cache
      uses: actions/cache@v1
      id: mix-cache #id to use in retrieve action
      with:
        path: deps
        key: ${{ runner.os }}-${{ env.OTP_VER }}-${{ env.ELIXIR_VER }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

    - name: Install Mix Dependencies
      if: steps.mix-cache.outputs.cache-hit != 'true'
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get

    - name: Check Formatting
      run: mix format --check-formatted

    - name: Run Credo
      run: mix credo --strict

    - name: Run Tests
      run: mix test

  deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: floms/action-caprover@v1
      with:
        app: 'botchini'
        host: 'https://captain.lucapasquale.dev'
        password: '${{ secrets.CAPROVER_PASSWORD }}'
        branch: 'main'
